### ISSUE TITLE
node-gyp rebuild error when installing word2vec

### ISSUE THREAD

**Issue by himangSharatun** [LeeXun/word2vector#1]
`gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 4.13.6-1-default
gyp ERR! command "/usr/bin/node8" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/yusuf/himang/Machine Learning/8Village/node_modules/word2vector
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN 8village@1.0.0 No description
npm WARN 8village@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! word2vector@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the word2vector@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-29T03_14_45_794Z-debug.log`

I got this error when i'm trying to install word2vec and I don't know what caused this error. Can you help me? thank before

**Comment by LeeXun** [comment]
Hello @himangSharatun 
It seems that it a permission issue.
Try execute `npm install` inside `./node_module/word2vector.`
Or check if you had used `sudo npm install` to install your project which made node-gyp don't have enough permission to execute.
Check [this thread](https://github.com/npm/npm/issues/2049) for more information.
