### ISSUE TITLE
w2v.similarity() returns wrong result

### ISSUE THREAD

**Issue by gscx233** [LeeXun/word2vector#6]
This function seems returns the **dot product** of two vectors instead of **cosine similarity** of the vectors. 

> A cosine similarity is a dot product divided by the product of norms.

```
w2v.similarity([0.1],[0.1])
0.010000000000000002
w2v.similarity([0.01],[0.01])
0.0001
w2v.similarity([0.02],[0.01])
0.0002
```

Issue seems to be at `calc.js` line 43, it just calculate the dot product and didn't divided by the product of norms.

```
......
  var sum = 0;
  for (i = 0; i < v1.length; i++) {
    sum += v1[i] * v2[i];
  }
  return sum;
......
```

**Comment by LeeXun** [comment]
Hello @hzhengran,

This function is mean to calculate the vectors returned by getVector function, which has already been normalized :) You can check more at the source code from google it self and I have some comment at [L108](https://github.com/LeeXun/word2vector/blob/master/src/w2vLeeXun.cc#L108), [L111](https://github.com/LeeXun/word2vector/blob/master/src/w2vLeeXun.cc#L111), [L130](https://github.com/LeeXun/word2vector/blob/master/src/w2vLeeXun.cc#L130), [L189](https://github.com/LeeXun/word2vector/blob/master/src/w2vLeeXun.cc#L189). Thanks.

**Comment by gscx233** [comment]
Thanks for the quick response!

However, when i tried to calculate two vectors' similarity, i got a number as below:
```
w2v.similarity([1,2,3],[1,2,3])
14
```
To my understading the similarity value should be between 0 and 1. And if the vectors are same, the value should be 1. 

Could you suggest how can I get the right result with this function? Many thanks!

**Comment by hzhengran** [comment]
And if i try to get the similarity of two vectors with same value, the result is not 1.

```
var v1 = v2 = [A 300 dimension vector]
w2v.similarity(v1,v2)
0.10785282179660252
```

**Comment by LeeXun** [comment]
Ahh, I mean the vectors you pass in similarity() should be a return value from getVector(), **getVector() will normalize the vector** (in those code I linked). You can't pass your own vector. I know that's a little bit tricky, but I suggest you to use other library or implement by yourself to calculate your own vector. w2v.similarity() is designed for this project only.  

Examples:
```
w2v.similarity(w2v.getVector("foo"), w2v.getVector(''bzz"))
# or
w2v.similarity("foo", "bzz")
```

**Comment by gscx233** [comment]
Sure, thanks a lot!
